import { AmenityCategory, AmenityCategoryEnum, Prisma } from '@prisma/client'

export const amenityCategories: AmenityCategory[] = [
  { code: 'bathroom', title: 'bathroom' },
  { code: 'bedroom', title: 'bedroom' },
  { code: 'family', title: 'family' },
  { code: 'heating', title: 'heating' },
  { code: 'safety', title: 'safety' },
  { code: 'internet', title: 'internet' },
  { code: 'dining', title: 'dining' },
  { code: 'outdoor', title: 'outdoor' },
  { code: 'parking', title: 'parking' },
  { code: 'services', title: 'services' },
  { code: 'views', title: 'views' },
  { code: 'entertainment', title: 'entertainment' },
]

export const amenities: (Omit<Prisma.ListingAmenityCreateInput, 'category'> & {
  category: AmenityCategoryEnum
})[] = [
  {
    title: 'Hair dryer',
    icon: '',
    description: '',
    category: 'bathroom',
  },
  {
    title: 'Cleaning products',
    icon: '',
    description: '',
    category: 'bathroom',
  },
  {
    title: 'Bathtub',
    icon: '',
    description: '',
    category: 'bathroom',
  },
  {
    title: 'Shampoo',
    icon: '',
    description: '',
    category: 'bathroom',
  },
  {
    title: 'Body soap',
    icon: '',
    description: '',
    category: 'bathroom',
  },
  {
    title: 'Hot water',
    icon: '',
    description: '',
    category: 'bathroom',
  },
  {
    title: 'Shower gel',
    icon: '',
    description: '',
    category: 'bathroom',
  },
  {
    title: 'Washer',
    icon: '',
    description: '',
    category: 'bedroom',
  },
  {
    title: 'Dryer',
    icon: '',
    description: '',
    category: 'bedroom',
  },
  {
    title: 'Essentials',
    icon: '',
    description: '',
    category: 'bedroom',
  },
  {
    title: 'Hangers',
    icon: '',
    description: '',
    category: 'bedroom',
  },
  {
    title: 'Iron',
    icon: '',
    description: '',
    category: 'bedroom',
  },
  {
    title: 'Bed linens',
    icon: '',
    description: '',
    category: 'bedroom',
  },
  {
    title: 'Extra pillows and blankets',
    icon: '',
    description: '',
    category: 'bedroom',
  },
  {
    title: 'Room-darkening shades',
    icon: '',
    description: '',
    category: 'bedroom',
  },
  {
    title: 'Clothing storage: closet',
    icon: '',
    description: '',
    category: 'bedroom',
  },
  {
    title: 'Crib',
    icon: '',
    description: '',
    category: 'family',
  },
  {
    title: 'Pack ’n play/Travel crib',
    icon: '',
    description: '',
    category: 'family',
  },
  {
    title: 'Children’s books and toys',
    icon: '',
    description: '',
    category: 'family',
  },
  {
    title: 'High chair',
    icon: '',
    description: '',
    category: 'family',
  },
  {
    title: 'Children’s dinnerware',
    icon: '',
    description: '',
    category: 'family',
  },
  {
    title: 'Indoor fireplace: wood-burning',
    icon: '',
    description: '',
    category: 'heating',
  },
  {
    title: 'Heating',
    icon: '',
    description: '',
    category: 'heating',
  },
  {
    title: 'Smoke alarm',
    icon: '',
    description: '',
    category: 'safety',
  },
  {
    title: 'Fire extinguisher',
    icon: '',
    description: '',
    category: 'safety',
  },
  {
    title: 'First aid kit',
    icon: '',
    description: '',
    category: 'safety',
  },
  {
    title: 'Wifi',
    icon: '',
    description: '',
    category: 'internet',
  },
  {
    title: 'Dedicated workspace',
    icon: '',
    description: 'In a common space',
    category: 'internet',
  },
  {
    title: 'Coffee maker',
    icon: '',
    description: '',
    category: 'dining',
  },
  {
    title: 'Freezer',
    icon: '',
    description: '',
    category: 'dining',
  },
  {
    title: 'Dishwasher',
    icon: '',
    description: '',
    category: 'dining',
  },
  {
    title: 'Stove',
    icon: '',
    description: '',
    category: 'dining',
  },
  {
    title: 'Hot water kettle',
    icon: '',
    description: '',
    category: 'dining',
  },
  {
    title: 'Toaster',
    icon: '',
    description: '',
    category: 'dining',
  },
  {
    title: 'Dining table',
    icon: '',
    description: '',
    category: 'dining',
  },
  {
    title: 'Barbecue utensils',
    icon: '',
    description: 'Grill, charcoal, bamboo skewers/iron skewers, etc.',
    category: 'dining',
  },
  {
    title: 'Blender',
    icon: '',
    description: '',
    category: 'dining',
  },
  {
    title: 'Baking sheet',
    icon: '',
    description: '',
    category: 'dining',
  },
  {
    title: 'Wine glasses',
    icon: '',
    description: '',
    category: 'dining',
  },
  {
    title: 'Stainless steel oven',
    icon: '',
    description: '',
    category: 'dining',
  },
  {
    title: 'Cooking basics',
    icon: '',
    description: 'Pots and pans, oil, salt and pepper',
    category: 'dining',
  },
  {
    title: 'Dishes and silverware',
    icon: '',
    description: 'Bowls, chopsticks, plates, cups, etc.',
    category: 'dining',
  },
  {
    title: 'Mini fridge',
    icon: '',
    description: 'Bowls, chopsticks, plates, cups, etc.',
    category: 'dining',
  },
  {
    title: 'Kitchen',
    icon: '',
    description: 'Space where guests can cook their own meals',
    category: 'dining',
  },
  {
    title: 'Refrigerator',
    icon: '',
    description: '',
    category: 'dining',
  },
  {
    title: 'Microwave',
    icon: '',
    description: '',
    category: 'dining',
  },
  {
    title: 'Patio or balcony',
    icon: '',
    description: '',
    category: 'outdoor',
  },
  {
    title: 'outdoor furniture',
    icon: '',
    description: '',
    category: 'outdoor',
  },
  {
    title: 'BBQ grill',
    icon: '',
    description: '',
    category: 'outdoor',
  },
  {
    title: 'outdoor dining area',
    icon: '',
    description: '',
    category: 'outdoor',
  },
  {
    title: 'Private backyard – Fully fenced',
    icon: '',
    description: 'An open space on the property usually covered in grass',
    category: 'outdoor',
  },
  {
    title: 'Free parking on premises',
    icon: '',
    description: '',
    category: 'parking',
  },
  {
    title: 'Free street parking',
    icon: '',
    description: '',
    category: 'parking',
  },
  {
    title: 'Private pool',
    icon: '',
    description: '',
    category: 'parking',
  },
  {
    title: 'Private living room',
    icon: '',
    description: '',
    category: 'parking',
  },
  {
    title: 'Private gym in building',
    icon: '',
    description: '',
    category: 'parking',
  },
  {
    title: 'Shared hot tub',
    icon: '',
    description: '',
    category: 'parking',
  },
  {
    title: 'Self check-in',
    icon: '',
    description: '',
    category: 'parking',
  },
  {
    title: 'Lockbox',
    icon: '',
    description: '',
    category: 'parking',
  },
  {
    title: 'Pets allowed',
    icon: '',
    description: 'Assistance animals are always allowed',
    category: 'services',
  },
  {
    title: 'Luggage dropoff allowed',
    icon: '',
    description:
      'For guests’ convenience when they have early arrival or late departure',
    category: 'services',
  },
  {
    title: 'Breakfast',
    icon: '',
    description: 'Breakfast is provided',
    category: 'services',
  },
  {
    title: 'Long term stays allowed',
    icon: '',
    description: 'Allow stay for 28 days or more',
    category: 'services',
  },
  {
    title: 'Garden view',
    icon: '',
    description: '',
    category: 'views',
  },
  {
    title: 'Lake view',
    icon: '',
    description: '',
    category: 'views',
  },
  {
    title: 'Park view',
    icon: '',
    description: '',
    category: 'views',
  },
  {
    title: 'Pool view',
    icon: '',
    description: '',
    category: 'views',
  },
  {
    title: 'River view',
    icon: '',
    description: '',
    category: 'views',
  },
  {
    title: 'Valley view',
    icon: '',
    description: '',
    category: 'views',
  },
  {
    title: 'TV',
    icon: '',
    description: '',
    category: 'entertainment',
  },
  {
    title: 'Piano',
    icon: '',
    description: '',
    category: 'entertainment',
  },
  {
    title: 'Books and reading material',
    icon: '',
    description: '',
    category: 'entertainment',
  },
]
