export enum CategoryEnum {
  'Mountains' = 1,
  'Landmarks' = 2,
  'Theaters' = 3,
  'Camps' = 4,
  'Tropical' = 5,
  'Amusements' = 6,
  'Meadows' = 7,
  'Deserts' = 8,
  'Shopping' = 9,
  'Windmills' = 10,
  'Museums' = 11,
  'Sailing' = 12,
  'Arctic' = 13,
  'Golfing' = 14,
  'Urban' = 15,
}
